#!/usr/bin/env python
from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

# Explicitly resolve and inject the paths
CURRENT_DIR = Path(__file__).resolve().parent
ROOT_DIR = CURRENT_DIR.parents[1]
sys.path.insert(0, str(CURRENT_DIR))
sys.path.insert(0, str(ROOT_DIR / "src"))

import torch
from torch_geometric.data import Data
from torch_geometric.data import Batch

# Now the import will cleanly resolve
from train_v26_pga_gp_electrochem_info import V20AGAAMotor, TARGET_INDEX, TARGET_NAME, normalize_y, MEV

def initialize_stoichiometry(formula: str, device: torch.device) -> torch.Tensor:
    atomic_numbers = {'H': 1, 'C': 6, 'N': 7, 'O': 8, 'F': 9}
    z_list = []
    
    import re
    tokens = re.findall(r'([A-Z][a-z]*)(\d*)', formula)
    for element, count in tokens:
        count = int(count) if count else 1
        if element not in atomic_numbers:
            raise ValueError(f"Element {element} not supported in this QM9 subset.")
        z_list.extend([atomic_numbers[element]] * count)
        
    return torch.tensor(z_list, dtype=torch.long, device=device)

def langevin_dynamics(
    model: torch.nn.Module,
    z: torch.Tensor,
    target_u0_norm: float,
    steps: int = 1000,
    lr_start: float = 0.1,
    lr_end: float = 1e-4,
    noise_start: float = 0.5,
    noise_end: float = 0.0,
    motor_regularization: float = 0.1,
):
    device = z.device
    N = z.size(0)
    
    pos = torch.randn(N, 3, device=device) * 2.0
    pos.requires_grad_(True)
    
    trajectory = []
    optimizer = torch.optim.Adam([pos], lr=lr_start)

    print(f"Initiating Langevin Dynamics for {N} atoms targeting normalized U0: {target_u0_norm:.4f}")

    for t in range(steps):
        frac = t / max(steps - 1, 1)
        current_lr = lr_start * (lr_end / lr_start) ** frac
        current_noise = noise_start * (1.0 - frac) + noise_end * frac
        
        for param_group in optimizer.param_groups:
            param_group['lr'] = current_lr

        optimizer.zero_grad()
        
        data = Data(z=z, pos=pos)
        batch = Batch.from_data_list([data]).to(device)
        
        pred_norm, motor_sig = model(batch, motor_strength=1.0)
        pred_u0 = pred_norm.view(-1)
        
        energy_loss = (pred_u0 - target_u0_norm).pow(2).mean()
        total_loss = energy_loss - motor_regularization * motor_sig
        
        total_loss.backward()
        torch.nn.utils.clip_grad_norm_([pos], max_norm=1.0)
        optimizer.step()
        
        with torch.no_grad():
            pos.add_(torch.randn_like(pos) * current_noise * math.sqrt(current_lr))
            center_of_mass = pos.mean(dim=0, keepdim=True)
            pos.sub_(center_of_mass)

        if t % 10 == 0 or t == steps - 1:
            print(f"Step {t:04d} | Pred U0: {pred_u0.item():.4f} | Motor Sig: {motor_sig.item():.2f} | Noise: {current_noise:.4f}")
            trajectory.append(pos.detach().cpu().clone())

    return pos.detach(), trajectory

def main():
    ap = argparse.ArgumentParser()
    # Changed required=True to default=None for dry runs
    ap.add_argument("--ckpt", default=None, help="Path to checkpoint (optional)")
    ap.add_argument("--formula", default="C6H6")
    ap.add_argument("--target-mev", type=float, default=0.0)
    ap.add_argument("--steps", type=int, default=2000)
    ap.add_argument("--out-xyz", default="generated_molecule.xyz")
    args = ap.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    model = V20AGAAMotor(
        num_layers=7, d_model=192, n_heads=16, n_rbf=20, out_dim=1
    ).to(device)
    
    if args.ckpt:
        print(f"Loading Electro-Chemical Metric Tensor from: {args.ckpt}")
        # Added weights_only=True to silence the PyTorch warning
        ckpt = torch.load(args.ckpt, map_location=device, weights_only=True)
        model.load_state_dict(ckpt["model_state_dict"])
    else:
        print("WARNING: No checkpoint provided. Initializing with RANDOM weights for dry run.")
        
    model.eval()

    target_norm = args.target_mev / MEV 
    z_tensor = initialize_stoichiometry(args.formula, device)
    
    final_pos, traj = langevin_dynamics(
        model=model, z=z_tensor, target_u0_norm=target_norm, steps=args.steps
    )
    
    z_list = z_tensor.cpu().numpy()
    atomic_symbols = {1: 'H', 6: 'C', 7: 'N', 8: 'O', 9: 'F'}
    
    print(f"Exporting optimized geometry to {args.out_xyz}")
    with open(args.out_xyz, "w") as f:
        f.write(f"{len(z_list)}\n")
        f.write(f"Generated by V26 Langevin Sampler. Target U0 Norm: {target_norm}\n")
        for i, atom_z in enumerate(z_list):
            sym = atomic_symbols.get(int(atom_z), 'X')
            x, y, z = final_pos[i].cpu().numpy()
            f.write(f"{sym} {x:.5f} {y:.5f} {z:.5f}\n")

if __name__ == "__main__":
    main()
